### ISSUE TITLE
Modificar el informe final para que las figuras queden mas cerca del texto. 

### ISSUE THREAD

**Issue by harpomaxx** [emiliano-f/time-series-forecasting-crypto#12]

**Comment by emiliano-f** [comment]
Se arregló el posicionamiento de figuras para el informe y sus anexos ([970ad98](https://github.com/emiliano-f/time-series-forecasting-crypto/commit/970ad9886b1fbd5899ed561a813144666ae6dd57) y [8e276c9](https://github.com/emiliano-f/time-series-forecasting-crypto/commit/8e276c9818cd315368013a15954b5bdd0c8eb67d)). Puede verse en los ultimos renderizados.
