### ISSUE TITLE
Armar una presentacion del proyecto 

### ISSUE THREAD

**Issue by harpomaxx** [emiliano-f/time-series-forecasting-crypto#13]
### GENERALIDADES
La presentacion la pueden hacer en la herramienta que consideren. Sin embago deberan generar un PDF de la misma y subirla a este repo
### SOBRE LA PRESENTACION
Amarr una presentacion en FORMAT PDF de unas  unas 20 slides (~15minutos.)

 La misma de incluir
1. Definicion del problema.
2. Metodos usados (generalidades, no quiero la teoria, sino sobre todo la diferencias.
3. Graficos con resultados y tablas
4. Conclusiones
   - Funcionan los metodos?
   - Cuando si funciona. CUando no fuciona?
   - Que metodo de los elegidos usarian.
5. Trabajos futuros.
   - Si tuvieran que seguir con el proyecto. Que harian?
   - Donde creen que se podria mejorar? 
   - Que otra tecnica les quedo por ver?

**Comment by emiliano-f** [comment]
Disponible en /doc/presentacion.pdf

Nota: Preguntas de la conclusión fueron movidas al item 2: metodos usados.
