### ISSUE TITLE
Artículos - Referencias web

### ISSUE THREAD

**Issue by emiliano-f** [emiliano-f/time-series-forecasting-crypto#2]
Listado de algunos artículos recopilados. Muchos con carácter de tutoriales. Síntesis junto a la cita.

**Comment by emiliano-f** [comment]
[https://www.askpython.com/python/examples/crypto-price-prediction](url)

Tutorial de predicción tomando Dogecoin, Python y API AutoTS. Utiliza módulos como numpy, pandas, matplotlib, y seaborn. El sitio provee un dataset bastante amigable.

**Comment by emiliano-f** [comment]
2. [https://medium.com/bitgrit-data-science-publication/ethereum-price-prediction-with-python-3b3805e6e512](url)

Capitalización de las criptomonedas. Los cuatro componentes de los datos en series de tiempo. Utiliza Prophet para el modelo y yfinance (Yahoo! Finance) como API para obtener datasets. Contiene amplias referencias.

**Comment by emiliano-f** [comment]
3. [https://towardsdatascience.com/demystifying-cryptocurrency-price-prediction-5fb2b504a110](url)

Utilización de precio histórico, cointegración y algunas variables macroeconómicas. Asegura aceptabilidad dentro de las 100 horas. Apartado sobre las causas de la variación de precios: favoritismo del mercado, condiciones políticas, percepción y aceptación pública.

Provee código y construcción del modelo. Alto nivel de detalle, **recomendado a las referencias del informe final**.

**Comment by emiliano-f** [comment]
4. [https://builtin.com/data-science/time-series-forecasting-python](url)

Métodos de predicción para series de tiempo: **ARMA, ARIMA, SARIMA**. Utiliza modulo statsmodels en Python. Tutorial bastante detallado y técnico.

**Comment by emiliano-f** [comment]
5. [https://tcoil.info/stock-and-cryptocurrency-price-prediction-with-python-prophet/](url)

Comparativa entre un modelo de machine learning con redes neuronales y biblioteca Prophet. Código detallado y varias referencias, especificamente **profundizan Prophet**.

**Comment by emiliano-f** [comment]
6. [https://www.godatainsights.com/post/cryptocurrency-ethereum-price-prediction-using-python](url)

Más sobre Prophet, yfinance y Ethereum. Tutorial.

**Comment by emiliano-f** [comment]
7. [https://thecleverprogrammer.com/2021/12/27/cryptocurrency-price-prediction-with-machine-learning/](url)

Más sobre yfinance, AutoTS. Tutorial.

**Comment by emiliano-f** [comment]
8. [https://levelup.gitconnected.com/how-i-tripled-my-return-on-bitcoin-using-mathematics-algorithms-and-python-347edd9b5625](url)

Tutorial donde utiliza un algoritmo llamado Golden Line. Interesante de cubrir como una alternativa. Provee un curso en Udemy sobre trading algorítmico.

**Comment by Mauro-1998** [comment]
http://190.169.30.62/bitstream/10872/19752/1/PrincipalTEG.pdf

Tutorial introductorio a Criptomonedas, Series Temporales y relación entre ambos

**Comment by emiliano-f** [comment]
9. https://towardsdatascience.com/multivariate-time-series-forecasting-with-transformers-384dc6ce989b

Series de tiempo multivariantes, con bastantes temas previos que se deben entender. A forma de tener una noción más compleja del problema.

**Comment by emiliano-f** [comment]
10. https://towardsdatascience.com/the-complete-guide-to-time-series-analysis-and-forecasting-70d476bfe775

Otra guía detallada sobre series temporales.

**Comment by Mauro-1998** [comment]
https://economipedia.com/definiciones/modelo-ar1.html

Explicación del método AR

**Comment by Mauro-1998** [comment]
12. https://economipedia.com/definiciones/modelo-autorregresivo-ar.html

Modelo de AR

**Comment by Mauro-1998** [comment]
13. https://www.rankia.cl/blog/analisis-ipsa/2039072-medias-movil-simple-exponencial-ponderada-formulas-ejemplos

Medias Móviles

**Comment by Mauro-1998** [comment]
14. https://es.wikipedia.org/wiki/Media_m%C3%B3vil#Media_m%C3%B3vil_simple

Otro articulo sobre Medias Móviles

**Comment by Mauro-1998** [comment]
15. https://economipedia.com/definiciones/modelo-arma.html

Modelo ARMA

**Comment by Mauro-1998** [comment]
16. https://relopezbriega.github.io/blog/2016/09/26/series-de-tiempo-con-python/

Series Temporales con Python

**Comment by Mauro-1998** [comment]
17. https://ichi.pro/es/analisis-de-series-de-tiempo-con-facebook-prophet-como-funciona-y-como-usarlo-265389504990778 

Prophet con Python

**Comment by Mauro-1998** [comment]
18. https://ri.itba.edu.ar/bitstream/handle/123456789/1230/TFI%20-%20Jose_%20Ignacio%20Lo_pez%20Sa_ez.pdf?sequence=1&isAllowed=y

Análisis y Explicación de Prophet

**Comment by emiliano-f** [comment]
https://towardsdatascience.com/cryptocurrency-price-prediction-using-deep-learning-70cfca50dd3a

Cryptocurrence Price Prediction Using Deep Learning (LSTM)

**Comment by emiliano-f** [comment]
Finalización de recopilación de fuentes
