### ISSUE TITLE
Listado de APIs

### ISSUE THREAD

**Issue by Mauro-1998** [emiliano-f/time-series-forecasting-crypto#4]

**Comment by emiliano-f** [comment]
https://github.com/winedarksea/AutoTS

AutoTS

Paquete de series de tiempo para Python, diseñado para ofrecer pronósticos de alta precisión rápidamente.

Todos los modelos admiten el pronóstico de múltiples series de tiempo y también admiten pronósticos probabilísticos (límite superior e inferior). La mayoría de los modelos pueden escalar fácilmente a decenas e incluso cientos de miles de series de entrada.

Algunos de estos modelos son: Zeroes Naive, Last Value Naive, Seasonal Naive, GLS, ARIMA, FBProphet, Univariate Regression, Multivariate Regression.

**Comment by emiliano-f** [comment]
https://www.coingecko.com/en/api

CoinGecko API

CoinGecko es un proveedor de datos y un sitio web de seguimiento de criptografía para precios en vivo, tickers, datos históricos, intercambios, eventos, volúmenes de negociación, mercados globales, información de monedas y más. Su API nos permite recuperar estos datos.

**Comment by emiliano-f** [comment]
https://pypi.org/project/yfinance/

yfinance

Yahoo Finance ofrece una excelente variedad de datos de mercado sobre acciones, bonos, divisas y criptomonedas. También ofrece noticias, informes y análisis del mercado y, además, opciones y datos fundamentales, que lo distinguen de algunos de sus competidores.

Ofrece granularidad fina de los datos (1/2/5 min) además de retornar datos directamente en dataframes pandas.

**Comment by emiliano-f** [comment]
https://pydata.github.io/pandas-datareader/index.html

pandas-datareader

Biblioteca utilizada para acceder a datos financieros públicos de Internet e importarlos a Python como dataframe pandas. Incorpora Yahoo Finance.

**Comment by Mauro-1998** [comment]
https://builtin.com/data-science/time-series-forecasting-python

Tutorial introductorio a los modelos ARMA, ARIMA y SARIMA

**Comment by Mauro-1998** [comment]
https://www.kaggle.com/taniaj/cryptocurrency-predictions-with-arima#ARIMAModel%22

Modelo ARIMA, Kaggle

**Comment by Mauro-1998** [comment]
https://facebook.github.io/prophet/docs/diagnostics.html#cross-validation

Prophet API Documentación

**Comment by emiliano-f** [comment]
Utilización de yfinance (datos). statsmodels (ARIMA), fbprophet (Prophet), keras (LSTM).
