### ISSUE TITLE
Crear documento en formato md o tex con las referencias

### ISSUE THREAD

**Issue by harpomaxx** [emiliano-f/time-series-forecasting-crypto#6]
Crear un documento los articulos/papers/videos/libros utilizados como material de lectura durante el proyecto.
O incluirlos en las referencias del informe final

**Comment by emiliano-f** [comment]
Las referencias estarán incluidas en el informe final. Además, se fueron incorporando a #2 y #3. Dado el presente desarrollo, aún no se han cerrado aquellos issues.
