### ISSUE TITLE
Analisis de resultados: Analizar las diferencias entre modelos.

### ISSUE THREAD

**Issue by harpomaxx** [emiliano-f/time-series-forecasting-crypto#7]
Para esto deberan utilizar alguna métrica como puede ser la correlacion entre las series.
**Opcional** (correr algun test estadistico para ver si son significativas las diferencias)

**Comment by emiliano-f** [comment]
Métricas utilizadas: Correlacion, MAE y MAPE sobre mismos periodos de tiempo.
