### ISSUE TITLE
Analisis de resultados: Diseño experimental:

### ISSUE THREAD

**Issue by harpomaxx** [emiliano-f/time-series-forecasting-crypto#8]
Probar con modelos generados a a partir de series de distintos tamaños
## Entrenamiento:
* Ultimo mes (elegir 10 meses al azar, y calcular media y desviación)
* La ultima semana (elegir 10 semanas al azar y calcular media y desviación)
* El Ultimo año (elegir 10 o los años que tengan en la db al azar y calcular media  desviación)
* Toda la serie
## Prediccion:
Asumiendo que el paso de la serie está dado por un dia de cotización:
* El dia siguiente 
* La semana siguiente
* El mes siguiente

**Comment by emiliano-f** [comment]
Tarea finalizada y expuesta en el informe. 
Entrenamiento: periodo de 7 y 30 dias al azar.
Predicción: la semana siguiente, para ambos casos.

**Comment by harpomaxx** [comment]
Esto y viendo en el informe y no veo los resultados de media y desviación standard. Sino que simplemente estan los 10 casos puntuales. Si bien esta bueno poder ver el detalle, hace falta un summary como para tener una idea de cual es la disperción. Entonces deberian presentar una tabla por cada modelo probado con media y desviacion. (Tal cual estaba en el issue).

**Comment by emiliano-f** [comment]
Añadimos las tablas y graficos de barras a los ejemplos presentes en el informe principal. El anexo II también se encuentran agregados tales tablas y graficos del ensayo con ARIMA. Pendiente, en el mencionado anexo, Prophet.
